# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
stages:
- stage: Build
  displayName: Build and Deploy
  jobs:
  - job: BuildAndDeploy
    displayName: BuildAndDeploy
    pool:
      name: Ubuntu
      vmImage: kst-VirtualBox
    workspace:
      clean: all

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: npm install
      displayName: 'npm install, build and test'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Pay-As-You-Go (0f5ce1a3-5d3c-463e-b9a8-d4743768aa5c)'
        appType: 'webAppLinux'
        WebAppName: 'ReactBankAppAPI'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        RuntimeStack: 'NODE|14-lts'